"""criando nova tabela de post

Revision ID: 8c06a730b5b8
Revises: 981e9614b124
Create Date: 2025-11-25 21:10:33.816137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c06a730b5b8'
down_revision = '981e9614b124'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=280),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=280),
               existing_nullable=False)

    # ### end Alembic commands ###
