"""primeira migração: Criação do Banco de Dados no Migrate

Revision ID: 981e9614b124
Revises: 
Create Date: 2025-11-24 14:10:25.828852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '981e9614b124'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_user', sa.String(length=20), nullable=False))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=256),
               existing_nullable=False)
        batch_op.drop_column('tipo_usuario')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_usuario', sa.INTEGER(), nullable=False))
        batch_op.alter_column('username',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
        batch_op.drop_column('type_user')

    # ### end Alembic commands ###
