"""title added to post table

Revision ID: d0e55c6faae0
Revises: 8c06a730b5b8
Create Date: 2025-11-27 10:47:52.957670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0e55c6faae0'
down_revision = '8c06a730b5b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=128), nullable=True))
        batch_op.execute("UPDATE posts SET title = 'testes'")
        batch_op.create_index(batch_op.f('ix_post_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_title'))
        batch_op.drop_column('title')

    # ### end Alembic commands ###
